// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_A5UhESCDudBNe9FAD_dSfTEnw2Larqk',
    appId: '1:223682990847:web:f23089b4b3e9b90c6432ca',
    messagingSenderId: '223682990847',
    projectId: 'chat-app-b1a7a',
    authDomain: 'chat-app-b1a7a.firebaseapp.com',
    storageBucket: 'chat-app-b1a7a.appspot.com',
    measurementId: 'G-TN2V2X7HR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKBrx8SBX8UBAXlyfhfwv-jE2zmx4EHfM',
    appId: '1:223682990847:android:e2b020c679f60b926432ca',
    messagingSenderId: '223682990847',
    projectId: 'chat-app-b1a7a',
    storageBucket: 'chat-app-b1a7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDylkrpwPDsdflHQOVCcHBXcQSsYZnFYY',
    appId: '1:223682990847:ios:0e091a2e048d2bf96432ca',
    messagingSenderId: '223682990847',
    projectId: 'chat-app-b1a7a',
    storageBucket: 'chat-app-b1a7a.appspot.com',
    iosClientId: '223682990847-eo9i6n97flbh0q61hrnvr7vpus0p5d3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDylkrpwPDsdflHQOVCcHBXcQSsYZnFYY',
    appId: '1:223682990847:ios:0e091a2e048d2bf96432ca',
    messagingSenderId: '223682990847',
    projectId: 'chat-app-b1a7a',
    storageBucket: 'chat-app-b1a7a.appspot.com',
    iosClientId: '223682990847-eo9i6n97flbh0q61hrnvr7vpus0p5d3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );
}
